version: "3"
services:
  api:
    image: 568237466542.dkr.ecr.us-west-2.amazonaws.com/polytomic-onprem:latest
    depends_on:
      - postgres
      - cache
    environment:
      - DEPLOYMENT
      - DEPLOYMENT_KEY
      - POLYTOMIC_URL
      - GOOGLE_CLIENT_ID
      - GOOGLE_CLIENT_SECRET
      - ROOT_USER=owner@acme.example.com
      - DATABASE_URL=postgres://owner:s3kr1t@postgres/polytomic
      - REDIS_URL=redis://cache:6379
      - PORT=5100
    ports:
      - "5100:5100"
  postgres:
    image: postgres:11
    restart: always
    environment:
      - POSTGRES_DB=polytomic
      - POSTGRES_USER=owner
      - POSTGRES_PASSWORD=s3kr1t
  cache:
    image: redis:6
